### ISSUE TITLE
No Issue but How to build this on a M5Core2

### ISSUE THREAD

**Issue by digi-thomas2003** [electricidea/M5Stack-Snow-Globe#1]
Hello,

this is a very lovely idea!!
And it is very easy to port it to a M5Core2: Just 3 steps to go

1. Just include the Core2 lib instead of M5stack: 
```c++
#include <M5Core2.h>
```

2. Comment out all defines before this - they are not necessary for the Core2

3. In the setup comment out the second line:
```c++
// M5.Power.begin();
```

Ready to go! Enjoy!
And thanks again for this nice idea!!

Best regards
Tom

**Comment by electricidea** [comment]
Hello Tom,
Thanks a lot. Very helpful.
I have extended the code so that you can choose between the three devices.
Thanks for the hint.

Hans-Günther
